"""Shared constants for the Streamlit health application."""

MODEL_FILES = {
    "diabetes_model": "models/diabetes_model.sav",
    "heart_model": "models/heart_disease_model.sav",
    "parkinson_model": "models/parkinsons_model.sav",
    "lung_cancer_model": "models/lung_cancer_model.sav",
    "breast_cancer_model": "models/breast_cancer.sav",
    "kidney": "models/kidney_disease.sav",
    "hepatitis_model": "models/hepititisc_model.sav",
    "liver_model": "models/liver_model.sav",
    "alzheimers_model": "models/alzheimers_model.sav",
    "epilepsy_model": "models/epilepsy_model.sav",
    "migraine_model": "models/migraine_model.sav",
    "tb_model": "models/tuberculosis_model.sav",
    "hiv_model": "models/hiv_model.sav",
    "malaria_model": "models/malaria_model.sav",
    "colorectal_model": "models/colorectal_model.sav",
    "prostate_model": "models/prostate_model.sav",
    "cervical_model": "models/cervical_model.sav",
    "asthma_model": "models/asthma_model.sav",
    "copd_model": "models/copd_model.sav",
    "pneumonia_model": "models/pneumonia_model.sav",
    "obesity_model": "models/obesity_model.sav",
}

DISEASE_ICONS = {
    "Home": "🏠",
    "🏠 Home": "🏠",
    "General Disease Prediction": "🔍",
    "Diabetes Prediction": "🩸",
    "Obesity Prediction": "⚖️",
    "Heart Disease Prediction": "❤️",
    "Parkinsons Prediction": "🧠",
    "Alzheimers Prediction": "🧩",
    "Epilepsy Prediction": "⚡",
    "Migraine Prediction": "💥",
    "Liver Prediction": "🧪",
    "Kidney Disease Prediction": "🫘",
    "Hepatitis Prediction": "🧪",
    "Tuberculosis Prediction": "🫁",
    "HIV/AIDS Prediction": "🧬",
    "Malaria Prediction": "🦟",
    "Lung Cancer Prediction": "🌬️",
    "Breast Cancer Prediction": "🎗️",
    "Colorectal Cancer Prediction": "🧬",
    "Prostate Cancer Prediction": "🧫",
    "Cervical Cancer Prediction": "🧫",
    "Asthma Prediction": "🌫️",
    "COPD Prediction": "😮‍💨",
    "Pneumonia Prediction": "🫁",
    "AI Health Assistant": "🤖",
    "Book Appointment": "📅",
    "Set Reminder": "⏰",
    "Health Tips": "💡",
}

HEALTH_TIPS = [
    "Drink at least 8 glasses of water daily.",
    "Exercise for at least 30 minutes a day.",
    "Eat a balanced diet rich in fruits and vegetables.",
    "Get at least 7-8 hours of sleep each night.",
    "Avoid smoking and limit alcohol consumption.",
    "Practice mindfulness and meditation to reduce stress.",
    "Regular health check-ups can prevent serious diseases.",
    "Maintain a healthy weight through balanced diet and exercise.",
    "Wash your hands frequently to prevent infections.",
    "Limit processed foods and sugar intake.",
    "Take breaks from screen time every hour.",
    "Practice good posture to prevent back problems.",
]
